on:
  push:

jobs:
  example_matrix:
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
      name: matrix-job
      runs-on: ${{matrix.os}}

      steps:
      - run: echo "Hello world"
